---
title: "wego_transit_analysis"
output: html_document
date: "2026-01-15"
---

```{r}
library(tidyverse)
library(dplyr)
library(lubridate)

wego <- read_csv("../data/Route 50 Timepoint and Headway Data, 1-1-2023 through 5-12-2025.csv")
```

```{r}
# Create new date time column
wego$DATE_TIME <- ymd(wego$DATE) + hms(wego$SCHEDULED_TIME)

# Examine Data
wego
```


```{r}
# Add day of week column
wego <- wego |>
  mutate(
    DATE_TIME = as.POSIXct(DATE_TIME),
    DAY_OF_WEEK = wday(DATE_TIME, 
                       label = TRUE, 
                       abbr = FALSE))

wego
```


```{r}

# Build indicator column for TSP time-frames
wego <- wego |>  mutate(
  tsp_indicator = if_else(
    between(DATE_TIME, 
            as.Date("2025-02-03 12:00:00"), 
            as.Date("2025-02-10 12:00:00")) |
    between(DATE_TIME, 
            as.Date("2025-02-10 12:00:00"), 
            as.Date("2025-04-28 12:00:00")) |
    between(DATE_TIME, 
            as.Date("2025-05-05 12:00:00"), 
            as.Date("2025-05-12 12:00:00")), 1, 0)
  )

```

```{r}
glimpse(wego)
```

```{r}
# Add hour column to data
wego_hr <- wego |> mutate(
  HOUR_COLUMN = hms(SCHEDULED_TIME) |> 
    hour()
  )
  
```

```{r}
# View ocurrences obscured by N/A values
wego_hr[is.na(wego_hr$HOUR_COLUMN),]

```

```{r}
# Adjust SCHEDULED_TIME values to be consistent throughout column
wego_hr$SCHEDULED_TIME = str_sub(
  wego_hr$SCHEDULED_TIME, 
  start = -8, 
  end = -1
  )

# Save to original dataframe
wego_hr <- wego |> mutate(
  HOUR_COLUMN = hms(SCHEDULED_TIME) |> 
    hour()
  )

wego_hr

```

```{r}
# Add time of day feature with hour column
wego_hr <- wego_hr |> mutate(
  time_of_day = case_when(
    HOUR_COLUMN >= 4 & HOUR_COLUMN < 6  ~ 'early_morning',
    HOUR_COLUMN >= 6 & HOUR_COLUMN < 9  ~ 'morning_peak',
    HOUR_COLUMN >= 9 & HOUR_COLUMN < 15 ~ 'midday',
    HOUR_COLUMN >= 15 & HOUR_COLUMN < 18 ~ 'pm_peak',
    HOUR_COLUMN >= 18 & HOUR_COLUMN < 21 ~ 'evening',
    TRUE ~ 'late_night')
  )

wego_hr
```

```{r}
# Show proportion of late buses by time of day
wego_hr |> 
  group_by(time_of_day) |> 
  summarize(mean(ADJUSTED_LATE_COUNT))
  
```


```{r}
# Fit logistic regression model based on tsp
wego_log_reg <- glm(ADJUSTED_LATE_COUNT ~ tsp_indicator,
                    data = wego,
                    family = "binomial")
wego_log_reg

summary(wego_log_reg)
```

```{r}
# Show percentage of late stops without tsp
predict(object = wego_log_reg, 
        newdata = data.frame(tsp_indicator = 0), 
        type= 'response') 

```

```{r}
# # Show percentage of late stops with tsp
predict(object = wego_log_reg, 
        newdata = data.frame(tsp_indicator = 1), 
        type= 'response') 

```


```{r}
# Fit model based on time of day
glm(ADJUSTED_LATE_COUNT ~ time_of_day,
                    data = wego_hr,
                    family = "binomial")
```

```{r}
# Add indicator column to wego_hr
wego_hr <- wego_hr |>  mutate(
  tsp_indicator = if_else(
    between(DATE_TIME, 
            as.Date("2025-02-03 12:00:00"), 
            as.Date("2025-02-10 12:00:00")) |
    between(DATE_TIME, 
            as.Date("2025-02-10 12:00:00"), 
            as.Date("2025-04-28 12:00:00")) |
    between(DATE_TIME, 
            as.Date("2025-05-05 12:00:00"), 
            as.Date("2025-05-12 12:00:00")), 1, 0)
  )

```


```{r}
time_day_log <- glm(ADJUSTED_LATE_COUNT ~ tsp_indicator * ROUTE_DIRECTION_NAME,
                    data = wego_hr,
                    family = "binomial")
```

```{r}
summary(time_day_log)
```


```{r}
l <- glm(ADJUSTED_LATE_COUNT ~ tsp_indicator * time_of_day,
                    data = wego_hr,
                    family = "binomial")
```

```{r}
summary(l)
```


```{r}
glm(ADJUSTED_LATE_COUNT ~ tsp_indicator + time_of_day,
                    data = wego_hr,
                    family = "binomial")
```


```{r}

late_prop_by_time <- wego_hr |>
  group_by(time_of_day) |>
  summarize(mean_late_count = mean(ADJUSTED_LATE_COUNT)) 


ggplot(late_prop_by_time, aes(x = time_of_day, y = mean_late_count)) +
  geom_col(fill = "#b5ffd0", color = "black") + 
  labs(
    title = "Average Late Count by Time of Day",
    x = "Time of Day",
    y = "Late Count Proportion"
  )

```

```{r}

avg_late_count_by_day <- ggplot(late_prop_by_time, aes(x = time_of_day, y = mean_late_count)) +
  geom_col(fill = "#b5ffd0", color = "black") + 
  labs(
    title = "Average Late Count by Time of Day",
    x = "Time of Day",
    y = "Late Count Proportion"
  )

ggsave(
  filename = "avg_late_count_by_day.png",
  plot = avg_late_count_by_day,
  width = 8,
  height = 5,
  dpi = 300
)
```


```{r}

late_prop_by_time <- wego_hr |>
  group_by(DAY_OF_WEEK) |>
  summarize(mean_late_count = mean(ADJUSTED_LATE_COUNT)) 


ggplot(late_prop_by_time, aes(x = DAY_OF_WEEK, y = mean_late_count, na.rm = TRUE)) +
  geom_col(fill = "#b5ffd0", color = "black") + 
  labs(
    title = "Average Late Count by Day of Week",
    x = "Day of Week",
    y = "Late Count Proportion"
  )

```


```{r}
avg_day_late_count <- ggplot(late_prop_by_time, aes(x = DAY_OF_WEEK, y = mean_late_count, na.rm = TRUE)) +
  geom_col(fill = "#b5ffd0", color = "black") + 
  labs(
    title = "Average Late Count by Day of Week",
    x = "Day of Week",
    y = "Late Count Proportion"
  )

ggsave(
  filename = "avg_day_late_count.png",
  plot = avg_day_late_count,
  width = 8,
  height = 5,
  dpi = 300
)

```


